### ISSUE TITLE
I have a few doubts

### ISSUE THREAD

**Issue by sujaldev** [neverpanic/podman-rootful-network#2]
Hi, I had a few doubts about this if you don't mind answering.

- Are either of these methods just as secure as running a simple rootless container?
- If so, is one of these methods more secure than the other?

Basically, what I'm trying to figure out is whether there exist any disadvantages to using these methods? Network performance of privileged containers and the security of rootless containers? It just sounds too good to not have any drawbacks.

**Comment by neverpanic** [comment]
> * Are either of these methods just as secure as running a simple rootless container?

That depends. Your container does not have the capability to modify any of the network configuration settings that would usually require `CAP_NET_ADMIN`, because it does not have that capability in the user namespace that owns the network namespace associated with the network interface. So from that point of view, this should be safe. However, the root account is obviously involved in this, and containers using this method will probably be able to open raw sockets on this network interface, which completely rootless containers would probably not be able to do.

> * If so, is one of these methods more secure than the other?

There is little difference between using `podman` with `--uidmap` and using this approach. `podman-rootful-network` does not run `podman` itself as root, so the total number of components running as root is clearly smaller. On the other hand, `podman` with `--uidmap` run as root is upstream functionality and will not break in newer versions of podman, where this might.

> Basically, what I'm trying to figure out is whether there exist any disadvantages to using these methods? Network performance of privileged containers and the security of rootless containers? It just sounds too good to not have any drawbacks.

I am not aware of any drawbacks of using `--uidmap` or running rootless containers and attaching network from outside from a security point of view. In fact, I'd encourage everybody to always use `--uidmap`, since there really is no reason not to IMHO.

**Comment by sujaldev** [comment]
Thanks for the explanation!
