### ISSUE TITLE
Use --userns=auto instead of --uidmap?

### ISSUE THREAD

**Issue by cbs228** [neverpanic/podman-rootful-network#3]
I understand your current recommendation for mapping uids to be something like this:

```bash
RUNAS="$SOME_USERNAME"
podman run \
    --rm -it \
    --uidmap="0:$(id -u "$RUNAS"):1" \
    --uidmap="1:$(grep -Po '(?<=^'"$RUNAS"':).*$' /etc/subuid | head -1)" \
    registry.fedoraproject.org/fedora:38
```

There are some problems with this approach:

1. You still run as `root` inside the container

   ```txt
   $ id
   uid=0(root) gid=0(root) groups=0(root)
   ```

   Even though this does not permit root *outside* of the container, the root user can still get up to mischief *inside* the container.

2. The root user still has capabilities inside the container

   ```txt
   $ capsh --print
   Current: cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_sys_chroot,cap_setfcap=ep
   ```

While some containers have a `USER` directive or switch their user at runtime, this causes problems with `--volume` bind mounts back to the host. Sometimes we want to share volume content with other containers, and it can help to have a predictable, system-backed uid:gid for this.

Instead, maybe this is more appropriate:

```bash
# create these mappings only if they don't exist
# this recommendation is per podman-run(1)'s --userns option
sudo bash -c "echo 'containers:2147483647:2147483648'>>/etc/subuid"
sudo bash -c "echo 'containers:2147483647:2147483648'>>/etc/subgid"
```

Then run your container as:

```bash
RUNAS="$SOME_USERNAME"
podman run \
    --rm -it \
    --cap-drop=ALL \
    --user "$(id -u "$RUNAS"):$(id -g "$RUNAS")" \
    --userns=auto:uidmapping="$(id -u "$RUNAS"):$(id -u "$RUNAS"):1",gidmapping="$(id -g "$RUNAS"):$(id -g "$RUNAS"):1" \
    registry.fedoraproject.org/fedora:38
```

* `--cap-drop=ALL` ensures that root in the container has no capabilities. Not all containers can run this way.

* `--user` manually specifies the uid:gid to run as. Not all containers can run this way.

* `--userns=auto:…` is roughly equivalent to `--userns=keep-id` for rootless users. If `$SOME_USERNAME` on the host has a uid of 1000, then inside the container we might see:

  ```txt
  $ cat /proc/self/uid_map 
        1000       1000          1
           0 2147485655       1000
        1001 2147486655         23
  ```

All containers created this way have a unique uid_map. This can either be an advantage or a disadvantage. You can accomplish the same thing via `--uidmap`, but you'll need to do some math.

**Comment by neverpanic** [comment]
> 1. You still run as `root` inside the container  
>  ```
>  $ id
>  uid=0(root) gid=0(root) groups=0(root)
>  ```  
>  Even though this does not permit root _outside_ of the container, the root user can still get up to mischief _inside_ the container.
>
> 2. The root user still has capabilities inside the container  
>  ```
>  $ capsh --print
>  Current: cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_sys_chroot,cap_setfcap=ep
>  ```

I am aware of this. However, this is also the default for docker, and there may be containers out there that expect this. It is always a better solution to run with just the privileges your container needs, but that's container-specific and not a general solution, while these recommendations are. A few years ago when I started running services in OpenShift, I was surprised at the number of Containerfiles I had to modify because they wouldn't run in OpenShift (which does not start containers as root).

I guess my point is: If you're pulling a random binary container from Docker Hub and run it, at least don't give it root privileges outside of the namespaces by following my recommendations.

Your recommendations are good, but you do point out the pitfall yourself (emphasis mine):

> * `--cap-drop=ALL` ensures that root in the container has no capabilities. **Not all containers can run this way**.
> * `--user` manually specifies the uid:gid to run as. **Not all containers can run this way**.

Not having capabilities in the container and running as an unprivileged user in the container are very good suggestions, and I wish they were known more widely, but they were not the goal of this project.
